name: 🐛 Bug
description: Reporte um problema
title: "bug: "
body:
  - type: checkboxes
    attributes:
      label: Pré-requisitos
      description: Por favor, confirme se você já realizou os passos abaixos antes de abrir esta issue.
      options:
        - label: Eu li o guia de boas práticas para [abrir uma issue](https://github.com/exact-magic/.github/.github/CONTRIBUTING.md#criar-uma-issue).
          required: true
        - label: Eu pesquisei por issues anteriores que já reportaram este problema, sem sucesso.
          required: true
  - type: textarea
    attributes:
      label: Comportamento atual
      description: Uma descrição clara do bug e como ele se manifesta.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Comportamento esperado
      description: Uma descrição clara do que você espera que aconteça.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Passos para reprodução
      description: Explique de forma detalhada os passos para reproduzir o problema.
    validations:
      required: true
  - type: input
    attributes:
      label: Trecho de código relevante
      description: Se você identificou o trecho de código onde o problema ocorre, cole a referência aqui.
      placeholder: https://github.com/...
  - type: textarea
    attributes:
      label: Informações adicionais
      description: Liste outras informações relevantes. Stack traces, issues relacionadas, sugestões de como corrigir, links de referência, etc.
